server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:2332/DB?createDatabaseIfNotExist=true
    username: root
    password: amin2005
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
